version: '3.8'
services:
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '50MB'
  # haproxy:
  #   image: haproxy
  #   restart: always
  #   ports:
  #     - 9999:9999
  #     - 8404:8404
  #   volumes:
  #     - ./haproxy:/usr/local/etc/haproxy
  #   depends_on:
  #     - api1
  #     - api2
  #   networks:
  #     - web
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: "50MB"
  api1: &api1
    container_name: app1
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
  api2:
    <<: *api1
    container_name: app2
    ports:
      - 3001:3000
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=wallet
    volumes:
      - ./docker/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - web
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "300MB"
  # db:
  #   image: postgres
  #   container_name: pg
  
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U rinha"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   environment:
  #     - POSTGRES_PASSWORD=rinha
  #     - POSTGRES_USER=rinha
  #     - POSTGRES_DB=rinha
  #   volumes:
  #     - ./docker/db/pg:/docker-entrypoint-initdb.d/
  #     - ./postgresql.conf:/etc/postgresql/postgresql.conf
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - web
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.8"
  #         memory: "300MB"
networks:
  web:
    driver: bridge