version: '3.8'
services:
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=wallet
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
